# Generated by Django 6.0.3 on 2026-04-01 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='is_completed',
        ),
    ]
