# Generated by Django 6.0.3 on 2026-04-04 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0007_card_estimated_hours_timeentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='priority',
            field=models.CharField(blank=True, choices=[('P0', 'P0'), ('P1', 'P1'), ('P2', 'P2'), ('P3', 'P3')], default='', max_length=2),
        ),
    ]
